package SegundoParcial;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class Test {
	public static void main(String[] args) {
//		Graph<String> g = new Graph<String>();
//		g.addVertex("A");
//		g.addVertex("B");
//		g.addVertex("C");
//		g.addVertex("D");
//		g.addVertex("E");
//		g.addVertex("F");
//		g.addArc("A", "B", 1);
//		g.addArc("A", "C", 1);
//		g.addArc("C", "B", 1);
//		g.addArc("B", "D", 1);
//		g.addArc("B", "E", 1);
//		g.addArc("C", "F", 1);
//		List<String> list1 = new ArrayList<String>();
//		list1.add("A");
//		list1.add("B");
//		list1.add("C");
//		list1.add("D");
//		list1.add("E");
//		list1.add("F");
//		List<String> list2 = new ArrayList<String>();
//		list2.add("A");
//		list2.add("B");
//		list2.add("C");
//		list2.add("E");
//		list2.add("F");
//		list2.add("D");
//		List<String> list3 = new ArrayList<String>();
//		list3.add("A");
//		list3.add("C");
//		list3.add("B");
//		list3.add("E");
//		list3.add("F");
//		list3.add("D");
//		List<String> list4 = new ArrayList<String>();
//		list4.add("C");
//		list4.add("A");
//		list4.add("B");
//		list4.add("F");
//		list4.add("E");
//		list4.add("D");
//		List<String> list5 = new ArrayList<String>();
//		list5.add("A");
//		list5.add("B");
//		list5.add("D");
//		list5.add("C");
//		list5.add("E");
//		list5.add("F");
//		List<String> list6 = new ArrayList<String>();
//		list6.add("A");
//		list6.add("B");
//		list6.add("C");
//		list6.add("T");
//		List<String> list7 = new ArrayList<String>();
//		list7.add("A");
//		list7.add("A");
//		list7.add("B");
//		list7.add("C");
//		list7.add("D");
//		list7.add("E");
//		list7.add("F");
//		List<String> list8 = new ArrayList<String>();
//		list8.add("B");
//		list8.add("C");
//		list8.add("F");
//		list8.add("A");
//		list8.add("D");
//		list8.add("E");
//		System.out.println("debe retornar true");
//		System.out.println(g.isBFS(list1));
//		System.out.println(g.isBFS(list2));
//		System.out.println(g.isBFS(list3));
//		System.out.println(g.isBFS(list4));
//		System.out.println("debe retornar false");
//		System.out.println(g.isBFS(list5));
//		System.out.println(g.isBFS(list6));
//		System.out.println(g.isBFS(list7));
//		System.out.println(g.isBFS(list8));
		
//		Graph<String> g = new Graph<String>();
//		g.addVertex("A");
//		g.addVertex("B");
//		g.addVertex("C");
//		g.addVertex("D");
//		g.addVertex("E");
//		g.addVertex("F");
//		g.addArc("A", "B", 8);
//		g.addArc("A", "D", 10);
//		g.addArc("A", "C", 1);
//		g.addArc("B", "C", 5);
//		g.addArc("B", "E", 9);
//		g.addArc("C", "E", 7);
//		g.addArc("C", "D", 6);
//		g.addArc("C", "F", 2);
//		g.addArc("E", "F", 4);
//		g.addArc("D", "F", 1);

		// Graph<String> g = new Graph<String>();
		// g.addVertex("A");
		// g.addVertex("B");
		// g.addVertex("C");
		// g.addVertex("D");
		// g.addVertex("E");
		// g.addVertex("F");
		// g.addVertex("G");
		// g.addArc("A", "B", 2);
		// g.addArc("A", "C", 2);
		// g.addArc("B", "D", 4);
		// g.addArc("C", "D", 4);
		// g.addArc("C", "F", 1);
		// g.addArc("D", "E", 1);
		// g.addArc("F", "E", 1);
		// g.addArc("F", "G", 2);
		// print(g.route("A"));

		 Graph<String> g = new Graph<String>();
		 g.addVertex("A");
		 g.addVertex("B");
		 g.addVertex("C");
		 g.addVertex("D");
		 g.addVertex("E");
		 g.addArc("A", "B", 1);
		 g.addArc("A", "C", 3);
		 g.addArc("B", "C", 1);
		 g.addArc("B", "D", 8);
		 g.addArc("C", "D", 2);
		 g.addArc("A", "E", 1);
		 g.addArc("E", "C", 1);
		 g.addArc("E", "D", 1);
		 System.out.println(g.countCycles());
		// System.out.println(g.countCycles("A"));

		// Automata automata = new Automata("q0", false);
		// automata.addState("q1", false);
		// automata.addState("q2", true);
		// automata.addState("q3", false);
		// automata.addState("q4", true);
		// automata.addTransition("a", "q0", "q1");
		// automata.addTransition("b", "q1", "q1");
		// automata.addTransition("b", "q1", "q2");
		// automata.addTransition("c", "q1", "q3");
		// automata.addTransition("a", "q3", "q4");
		// System.out.println("estos tienen que ser false");
		// System.out.println(automata.isAccepted("a"));
		// System.out.println(automata.isAccepted("ad"));
		// System.out.println(automata.isAccepted("abbba"));
		// System.out.println(automata.isAccepted("abbcab"));
		// System.out.println(automata.isAccepted("abbbc"));
		// System.out.println("estos tienen que ser true");
		// System.out.println(automata.isAccepted("ab"));
		// System.out.println(automata.isAccepted("abb"));
		// System.out.println(automata.isAccepted("abbbb"));
		// System.out.println(automata.isAccepted("abbbca"));
	}

	private static void print(HashMap<String, String> route) {
		for (String key : route.keySet()) {
			System.out.print(key + " " + route.get(key));
			System.out.println("");
		}
	}
}
